CREATE TABLE IF NOT EXISTS complaints (
  id VARCHAR(191) PRIMARY KEY NOT NULL,
  campus_id VARCHAR(64) NOT NULL,
  description TEXT NOT NULL,
  latitude DOUBLE PRECISION NOT NULL,
  longitude DOUBLE PRECISION NOT NULL,
  media_path VARCHAR(1024),
  media_kind VARCHAR(24),
  media_mime_type VARCHAR(191),
  media_size_bytes INTEGER,
  public_name VARCHAR(191),
  status VARCHAR(24) NOT NULL DEFAULT 'pending',
  created_at VARCHAR(40) NOT NULL,
  moderated_at VARCHAR(40),
  approved_at VARCHAR(40),
  submitter_email VARCHAR(191)
);

CREATE INDEX IF NOT EXISTS complaints_status_idx
  ON complaints (status);

CREATE INDEX IF NOT EXISTS complaints_campus_status_idx
  ON complaints (campus_id, status);

CREATE INDEX IF NOT EXISTS complaints_created_at_idx
  ON complaints (created_at);

CREATE INDEX IF NOT EXISTS complaints_campus_created_at_idx
  ON complaints (campus_id, created_at);

CREATE TABLE IF NOT EXISTS submission_rate_limits (
  id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  key_hash VARCHAR(128) NOT NULL,
  created_at VARCHAR(40) NOT NULL,
  expires_at VARCHAR(40) NOT NULL
);

CREATE INDEX IF NOT EXISTS submission_rate_limits_key_hash_expires_at_idx
  ON submission_rate_limits (key_hash, expires_at);

CREATE INDEX IF NOT EXISTS submission_rate_limits_expires_at_idx
  ON submission_rate_limits (expires_at);
